### ISSUE TITLE
The ! system is too simple

### ISSUE THREAD

**Issue by nexinex** [TodePond/DreamBerd#255] opened 2023-07-17 18:59 UTC
As is, you've mostly just replaced semicolons with !. This is not good enough. I propose an alternate solution. Using more ! marks your line of code as more important. Within its own scope, lines of code with more ! will be run first. For example:
print("Fee")!
print("Fi")!!!
print("Fo")!!
print("Fum")!!!!
would print Fum Fi Fo Fee
As is right now, it's simply too sane to be functional, and I will need this update before adopting the language.

**Comment by stohrendorf** [comment] 2023-07-18 04:08
Duplicate of #241

**Closed** 2023-07-18 13:40 UTC
